blog/urls.py
from django.urls import path
from .import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
	# Обработчики приложения блога.
	path('', views.post_list, name='post_list'),
	# path('', views.PostListView.as_view(), name='post_list'),
	path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),

	path('<int:year>/<int:month>/<int:day>/<slug:post>/',
		views.post_detail, name='post_detail'),
	path('<int:post_id>/share/', views.post_share, name='post_share'),
	path('feed/', LatestPostsFeed(), name='post_feed'),

	path('create/', views.create_post, name='create_post'),
	path('my_posts', views.my_posts, name='my_posts'),
	path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),

	path('journal/', views.journal, name='journal'),
	path('like/', views.post_like, name='like')


	
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {'posts': PostSitemap, }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
    	name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('videos/', include('videos.urls', namespace='videos')),
    path('search/', include('search.urls', namespace='search'))
   

   
   
   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


search/urls.py
from django.urls import path
from .import views

app_name = 'search'

urlpatterns = [
	path('search/', views.search, name='search_mysite'),
]

videos/urls.py
from django.urls import path
from .import views

app_name = 'videos'

urlpatterns = [
	path('list/', views.list_videos, name='list_videos'),
	path('detail/<int:id_video>/<slug:slug>/',
		 views.detail_videos, name='detail_videos'),
	path('create/', views.create_video,
		 name='create'),
	path('edit/<int:id_video>/', views.edit_video,
		 name='edit'),
	path('videos/', views.my_video,
		 name='my_video'),
	path('video/share/<int:video_id>/', views.video_share,
		 name='video_share'),
	path('like/', views.video_like,
		 name='like')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.conf import settings 

# Create your models here.

# Менеджер моделя POST
class PublishedManager(models.Manager):
	def get_queryset(self):
		return super().get_queryset().filter(status='published')

# Модель для Постов
class Post(models.Model):
	objects = models.Manager()
	published = PublishedManager()
	tags = TaggableManager()
	

	STATUS_CHOICES = (
		('draft', 'Draft'),
		('published', 'Published'),

		)
	


	title = models.CharField(max_length=40)
	slug = models.SlugField(max_length=250, unique_for_date='publish')
	author = models.ForeignKey(User, on_delete=models.CASCADE,
								related_name='blog_posts')
	body = models.TextField()
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	image = models.ImageField(upload_to="images/%Y/%m/%d", blank=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10,
							  choices=STATUS_CHOICES,
							  default='draft')

	users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
										related_name='blog_like',
										blank=True)
	total_likes = models.PositiveIntegerField(db_index=True,
											  default=0)
	
	class Meta:
		ordering = ('-publish' ,)
	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post_detail', args=[self.publish.year,
						self.publish.month, self.publish.day, self.slug])

# Модель для комментариев
class Comment(models.Model):
	post = models.ForeignKey(Post, 
							 on_delete=models.CASCADE,
							 related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now_add=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('created' ,)
	def __str__(self):
		return 'Comment by {} on {}'.format(self.name, self.post)


blog/forms.py
from django import forms
from .models import Comment, Post

# Форма отправки письмо по email
class EmailPostForm(forms.Form):
	name = forms.CharField(max_length=25)
	#email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False, widget=forms.Textarea)

# Форма комментирование
class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('email', 'body')



# Форма Создание Поста
class CreatePostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('tags', 'title', 'slug',
				  'body', 'publish', 'image',
				  'status')


blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage,\
								  PageNotAnInteger
from .models import Post, Comment
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, \
								  CreatePostForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .tasks import comment_add
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from videos.models import VideoModel



# Обработчик для отправки письмо по Email
def post_share(request, post_id):
	# Получение статьи по идентификатуру.
	post = get_object_or_404(Post, id=post_id, status='published')
	sent = False
	if request.method == 'POST':
		# Форма была отправлена на сохранение.
		form = EmailPostForm(request.POST)
		if form.is_valid():
			# Все поля формы прошли валидацию
			cd = form.cleaned_data
			# Отправка электронной почты.
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], 
														    'kajnazarov06@mail.ru', 
				                            			    post.title)
			message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, 
															 post_url, 
				               								 cd['name'], 
															 cd['comments'])
			send_mail(subject, message, 
				      'kajnazarov06@mail.ru', [cd['to']])
			sent = True
	else:
		form = EmailPostForm()
	return render(request, 'blog/post/share.html',
				{'post': post, 
				 'form': form, 
				 'sent': sent})

# обработчик для главной страницы
class PostListView(ListView):
	queryset = Post.published.all()
	context_object_name = 'posts'
	paginate_by = 3
	template_name = 'blog/post/list.html'

# обработчик для главной страницы
def post_list(request, tag_slug = None):
	object_list = Post.published.all()
	tag = None

	if tag_slug:
		tag = get_object_or_404(Tag, slug = tag_slug)
		object_list = object_list.filter(tags__in = [tag])		

	paginator = Paginator(object_list, 3) # По 4 статьи на каждой странице.
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		# Если страница не является целым числом, возвращаем первую страницу.
		posts = paginator.page(1)
	except EmptyPage:
		# Если намер страницы больше, чем общее количество страниц, возвращаем последнюю.
		posts = paginator.page(paginator.num_pages)
	return render(request, 
				  'blog/post/list.html', 
				  {'page': page, 
				   'posts': posts,
				   'tag': tag})

# обрабочик для детального преставление 
def post_detail(request, year, month, day, post, tag_slug = None):
	object_list = Post.published.all()
	tag = None

	if tag_slug:
		tag = get_object_or_404(Tag, slug = tag_slug)
		object_list = object_list.filter(tags__in = [tag])
	


	post = get_object_or_404(Post, slug=post, 
								   status='published', 
							       publish__year=year,
							       publish__month=month,
							       publish__day=day)
	# Список активных комментариев для этой статьи.
	comments = post.comments.filter(active=True)
	new_comment = None
	if request.method == 'POST':
		# Пользователь отправил комментарий.
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			# Создаем комментарий, но покане сохраняем в базе данных.
			new_comment = comment_form.save(commit=False)
			new_comment.name = request.user.username
			# Привязываем комментарий к текущей статье.
			new_comment.post = post
			# Сохраняем комментарий в базе данных.
			new_comment.save()
			comment_add(new_comment.id)
	else:
		comment_form = CommentForm()

	# Формирование списка похожих статей.
	post_tags_ids = post.tags.values_list('id', flat=True)
	similar_posts = Post.published.filter(tags__in = post_tags_ids)\
								  .exclude(id = post.id)
	similar_posts = similar_posts.annotate(same_tags = Count('tags'))\
								  .order_by('-same_tags', '-publish')[:4]

	return render(request, 
		          'blog/post/detail.html', 
		          {'post': post,
				   'comments': comments,
				   'new_comment': new_comment,
				   'comment_form': comment_form,
				   'similar_posts': similar_posts,
				   'tag': tag,})

# обрабочик создание постов
@login_required
def create_post(request):
	if request.method == 'POST':
		create_form = CreatePostForm(data=request.POST,
									 files=request.FILES)
		if create_form.is_valid():
			new_post = create_form.save(commit=False)
			new_post.author = request.user
			new_post.save()
			messages.success(request, 'Post created successfully')
		else:
			messages.error(request, 'Error when creating a post')
	else:
		create_form = CreatePostForm()

	context = {'create_form': create_form}
	return render(request, 
		          'blog/post/create_post.html', 
		         context)

# обрабочик для сортирования личных постов
@login_required
def my_posts(request):
	posts = Post.objects.filter(author=request.user.id)
	paginator = Paginator(posts, 3)
	page = request.GET.get('page')

	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		if request.is_ajax():
			return HttpResponse('')
			posts = paginator.page(paginator.num_pages)

	if request.is_ajax():
		return render(request,
					  'blog/post/my_posts_ajax.html',
					  {'posts': posts})
		
	return render(request, 
		          'blog/post/my_posts.html', 
		          {'posts': posts})

# обрабочик для редактирования постов
@login_required
def edit_post(request, post_id):
	post = Post.objects.get(id=post_id)
	
	if request.method == 'POST':
		post_form = CreatePostForm(instance=post,
								   data=request.POST,
								   files=request.FILES)
		
		if post_form.is_valid():
			post_form.save()
			messages.success(request, 'Post saved successfully')
		else:
			messages.error(request, 'Error while saving post')
	else:
		post_form = CreatePostForm(instance=post)

	return render(request, 
		          'blog/post/edit_post.html', 
		          {'post_form': post_form,
				   'post': post,})

# Обрабочик описание журнала
def journal(request):
	return render(request, 
		          'blog/journal/about_journal.html')

@login_required
@require_POST
def post_like(request):
	post_id = request.POST.get('id')
	action = request.POST.get('action')
	try:
		post = Post.objects.get(id=post_id)
		if action == "like":
			post.users_like.add(request.user)
		else:
			post.users_like.remove(request.user)
		return JsonResponse({'status': 'ok'})
	except:
		pass
	return JsonResponse({'status': 'ok'})



blog/templates/blog/base.html
{% load blog_tags %}
{% load bootstrap5 %}
{% load static %}
<!doctype html>
<html lang="ru">
	<head>
	<!-- Обязательные метатеги -->
	<meta charset="utf-8">
	<meta name="viewport" 
		  content="width=device-width,
		  		   initial-scale=1">
	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
		  rel="stylesheet" 
		  integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
		  crossorigin="anonymous">
	<!--Меню-->
	<nav class="navbar navbar-expand-lg navbar-light bg-light rounded"
		 aria-label="Eleventh navbar example">
		<div class="container-fluid">
			<button class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarsExample10"
					aria-controls="navbarsExample10"
					aria-expanded="false"
					aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<a class="navbar-brand" 
			   href="{% url 'blog:post_list' %}">
				<span class="mb-0 h1" 
					  style="font-size: 50px">
					  Interstellar
				</span>
			</a>
			<div class="collapse navbar-collapse justify-content-md-center"
				 id="navbarsExample10">
				<ul class="navbar-nav me-auto mb-3 mb-lg-0">
					<li class="nav-item">
						{% if request.user.is_authenticated %}
							<a class="nav-link active" 
							   style="height: 29px"
							   href="{% url 'my_account' %}">
							   My Account
							   <svg xmlns="http://www.w3.org/2000/svg"
									width="20"
									height="20"
									fill="currentColor"
									class="bi bi-person-circle"
									viewBox="0 0 16 16">
									<path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
									<path fill-rule="evenodd"
									d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
								</svg>
							</a>
						{% else %}
							<a class="nav-link active"
							   style="height: 29px"
							   href="{% url 'login' %}">
							   Login
							   <svg xmlns="http://www.w3.org/2000/svg"
									width="20"
									height="20"
									fill="currentColor"
									class="bi bi-person"
									viewBox="0 0 16 16">
									<path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
								</svg>
							</a>
						{% endif %}
					</li>
				</ul>
				<a href="{% url 'search:search_mysite' %}">
					<button type="button"
							class="btn btn-primary">
							<svg xmlns="http://www.w3.org/2000/svg"
								 width="16"
								 height="16"
								 fill="currentColor"
								 class="bi bi-search"
								 viewBox="0 0 16 16">
								<path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
							</svg>
							Search
					</button>
				</a>
			</div>
		</div>
	</nav> 
	<div class="border-top"></div>
	<nav class="navbar navbar-expand-lg navbar-light bg-light rounded"
		 aria-label="Eleventh navbar example">
		<ul class="nav">
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle fw-bold"
				   href="#"
				   id="dropdown09"
				   data-bs-toggle="dropdown"
				   aria-expanded="false"
				   style="color: black; text-decoration:none">
				   Videos
				</a>
				<ul class="dropdown-menu bg-dark"
					aria-labelledby="dropdown09">
					<li>
						<a class="dropdown-item fw-bold"
						   href="{% url 'videos:list_videos' %}"
						   style="color: #ffffff; font-size: 14px">
						   List Videos
						</a>
					</li>
					<li>
						<a class="dropdown-item fw-bold"
						   style="color: #ffffff; font-size: 14px"
						   href="{% url 'videos:create' %}">
						   Create Video
						</a>
					</li>
					<li>
						<a class="dropdown-item fw-bold"
						   style="color: #ffffff; font-size: 14px"
						   href="{% url 'videos:my_video' %}">
						   My Videos
						</a>
					</li>
				</ul>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle fw-bold"
				   href="#"
				   id="dropdown09"
				   data-bs-toggle="dropdown"
				   aria-expanded="false"
				   style="color: black; text-decoration:none">
				   Journal information
				</a>
				<ul class="dropdown-menu bg-dark"
					aria-labelledby="dropdown09">
					<li>
						<a class="dropdown-item fw-bold"
						   style="color: #ffffff; font-size: 14px"
						   href="{% url 'blog:journal' %}">
					 	   About the Journal
						</a>
					</li>
				</ul>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle fw-bold"
				   href="#"
				   id="dropdown09"
				   data-bs-toggle="dropdown"
				   aria-expanded="false"
				   style="color: black; text-decoration:none">
				   Publish with us
				</a>
				<ul class="dropdown-menu bg-dark"
				    aria-labelledby="dropdown09">
					<li>
						<a class="dropdown-item fw-bold"
						   href="{% url 'blog:my_posts' %}"
						   style="color: #ffffff; font-size: 14px">
						   My posts
						</a>
					</li>
					<li>
						<a class="dropdown-item fw-bold"
						   href="{% url 'blog:create_post' %}"
						   style="color: #ffffff; font-size: 14px">
 						   Submit manuscript
						</a>
					</li>
				</ul>
			</li>
		</ul>
	</nav>
	<div class="pb-2 border-top"></div>
	<style>
		a { 
			text-decoration: none; /* Отменяем подчеркивание у ссылки */
		  } 
	</style>
	</head>
	<body>
		{% block content %}{% endblock %}
		<!-- Необязательный JavaScript; выберите один из двух! -->
		<!-- Вариант 1: пакет Bootstrap с Popper -->
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
				integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
				crossorigin="anonymous">
		</script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
		<!-- скрипт для ajax запросов -->
		<script>
			var csrftoken = Cookies.get('csrftoken');
			function csrfSafeMethod(method) {
				// Для этих методов токен не будет подставляться в заголовок.
				return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
			}
			$.ajaxSetup({
				beforeSend: function(xhr, settings) {
					if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
					xhr.setRequestHeader("X-CSRFToken", csrftoken);
					}
				}
			});
			$(document).ready(function () {
				{% block domready %}{% endblock %}
			});
		</script>
	</body>
	<footer>
		<nav class="navbar navbar-dark bg-dark">
			<div class="container-fluid">
				<a class="navbar-brand">
					<span class="mb-0 h6" 
						  style="font-size: 15px">
						  Springe Interstellar
					</span>
				</a>
				<a class="navbar-text">
					<span class="mb-0 h6" 
						  style="font-size: 12px">
						  © 2021 Springer Nature Limited
					</span>
				</a>
			</div>
		</nav>
	</footer>
</html>
