blog/urls.py
from django.urls import path
from .import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
	# Обработчики приложения блога.
	path('', views.post_list, name='post_list'),
	# path('', views.PostListView.as_view(), name='post_list'),
	path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),

	path('<int:year>/<int:month>/<int:day>/<slug:post>/',
		views.post_detail, name='post_detail'),
	path('<int:post_id>/share/', views.post_share, name='post_share'),
	path('feed/', LatestPostsFeed(), name='post_feed'),

	path('create/', views.create_post, name='create_post'),
	path('my_posts', views.my_posts, name='my_posts'),
	path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),

	path('journal/', views.journal, name='journal'),
	path('like/', views.post_like, name='like')


	
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {'posts': PostSitemap, }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
    	name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('videos/', include('videos.urls', namespace='videos')),
    path('search/', include('search.urls', namespace='search'))
   

   
   
   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


videos/urls.py
from django.urls import path
from .import views

app_name = 'videos'

urlpatterns = [
	path('list/', views.list_videos, name='list_videos'),
	path('detail/<int:id_video>/<slug:slug>/',
		 views.detail_videos, name='detail_videos'),
	path('create/', views.create_video,
		 name='create'),
	path('edit/<int:id_video>/', views.edit_video,
		 name='edit'),
	path('videos/', views.my_video,
		 name='my_video'),
	path('video/share/<int:video_id>/', views.video_share,
		 name='video_share'),
	path('like/', views.video_like,
		 name='like')
]

videos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.conf import settings
# Create your models here.

# Модель для сохраненеи видеоматериалов
class VideoModel(models.Model):
	tags = TaggableManager()

	author = models.ForeignKey(User, on_delete=models.CASCADE,
							   related_name='video_model')
	title = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200, blank=True)
	poster = models.ImageField(upload_to='uploads/%Y/%m/%d')
	upload = models.FileField(upload_to='uploads/%Y/%m/%d')
	body  = models.TextField(blank=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now_add=True)

	users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
										related_name='video_like',
										blank=True)
	total_likes = models.PositiveIntegerField(db_index=True,
											  default=0)

	def __str__(self):
		return '{}'.format(self.title)
	
	def get_absolute_url(self):
		return reverse('videos:detail_videos', args=[self.id,
										      self.slug])

class Comment(models.Model):
	video = models.ForeignKey(VideoModel,
							  on_delete=models.CASCADE,
							  related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now_add=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('created' ,)

	def __str__(self):
		return 'Comment by {} on {}'.format(self.name, self.video)

videos/forms.py
from django import forms
from .models import VideoModel, Comment

# Форма для работы с ВидеоМоделью
class Videoform(forms.ModelForm):
	class Meta:
		model = VideoModel
		fields = (
			'tags', 'title',
			'slug', 'poster',
			'upload', 'body'
			)

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = (
			'email', 'body'
			)

class VideoShareForm(forms.Form):
	name = forms.CharField(max_length=25)
	to = forms.EmailField()
	comments = forms.CharField(required=False, 
							   widget=forms.Textarea)

videos/views.py
from django.shortcuts import render, get_object_or_404
from .models import VideoModel, Comment
from taggit.models import Tag
from django.db.models import Count
from .forms import Videoform, CommentForm, VideoShareForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .tasks import comment_add
from django.core.mail import send_mail
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage,\
								  PageNotAnInteger
from django.http import JsonResponse
from django.views.decorators.http import require_POST
# Create your views here.

# Список видеосов
def list_videos(request):
	videos = VideoModel.objects.all()
	paginator = Paginator(videos, 8)
	page = request.GET.get('page')
	try:
		videos = paginator.page(page)
	except PageNotAnInteger:
		videos = paginator.page(1)
	except EmptyPage:
		if request.is_ajax():
			return HttpResponse('')
		videos = paginator.page(paginator.num_pages)
	if request.is_ajax():
		return render(request,
					  'videos/videos/list_ajax.html',
					  {'videos': videos})
	return render(request,
				  'videos/videos/list_videos.html',
				  {'videos': videos})

# Детальное преставление видео
def detail_videos(request, id_video, slug, tags_slug=None):
	object_list = VideoModel.objects.all()
	tag = None
	videos = get_object_or_404(VideoModel, 
							   id=id_video,
							   slug=slug)
	if tags_slug:
		tag = get_object_or_404(Tag, slug = tags_slug)
		object_list = object_list.filter(tag__in = [tag])

	# Формирование похожих видеоматеривлов
	videos_tags_ids = videos.tags.values_list('id', flat=True)
	similar_videos = VideoModel.objects.filter(tags__in=videos_tags_ids)\
											   .exclude(id=videos.id)
	similar_videos = similar_videos.annotate(same_tags=Count('tags'))\
											 .order_by('-same_tags')[:4]

	comments = Comment.objects.filter(active=True)
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			new_comment = form.save(commit=False)
			new_comment.name = request.user.username
			new_comment.video = videos
			new_comment.save()
			comment_add(new_comment.id)
	else:
		form = CommentForm()

	return render(request,
				  'videos/videos/detail_videos.html',
				  {'videos': videos,
				   'similar_videos': similar_videos,
				   'tag': tag,
				   'form': form,
				   'comments': comments})

	

# Создание видео
@login_required
def create_video(request):
	if request.method == 'POST':
		form = Videoform(data=request.POST,
						 files=request.FILES)
		if form.is_valid():
			new_video = form.save(commit=False)
			new_video.author = request.user
			new_video.save()
			messages.success(request, 'Video added successfully')
		else:
			messages.error(srequest, 'Error adding video')
	else:
		form = Videoform()
	return render(request,
				  'videos/videos/create.html',
				  {'form': form})

# Сортировка видеосов пользователя
@login_required
def my_video(request):
	videos = VideoModel.objects.all()
	my_videos = videos.filter(author=request.user)

	paginator = Paginator(my_videos, 8)
	page = request.GET.get('page')
	try:
		my_videos = paginator.page(page)
	except PageNotAnInteger:
		my_videos = paginator.page(1)
	except EmptyPage:
		if request.is_ajax():
			return HttpResponse('')
		my_videos = paginator.page(paginator.num_pages)
		
	if request.is_ajax():
		return render(request,
					  'videos/videos/my_videos_ajax.html',
					  {'my_videos': my_videos})

	return render(request,
				  'videos/videos/my_videos.html',
				  {'my_videos': my_videos}) 

# редактирование видеоматериалов
@login_required
def edit_video(request, id_video):
	video = VideoModel.objects.get(id=id_video)
	if request.method == 'POST':
		form = Videoform(instance=video,
						 data=request.POST,
						 files=request.FILES)
		if form.is_valid():
			form.save()
			messages.success(request, 'Change saved succesfully')
		else:
			messages.error(request, 'Save Error')
	else:
		form = Videoform(instance=video)
	return render(request,
				  'videos/videos/edit.html',
				  {'form': form})

def video_share(request, video_id):
	video = VideoModel.objects.get(id=video_id)
	sent = False
	if request.method == 'POST':
		form = VideoShareForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			video_url = request.build_absolute_uri(video.get_absolute_url())
			subject = '{} ({}) recommends you reading "{}"'.format(cd['name'],
															'kajnazarov06@mail.ru',
															video.title)
			message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(video.title, 
															  video_url,
															  cd['name'],
															  cd['comments'])
			send_mail(subject, message,
					  'kajnazarov06@mail.ru', [cd["to"]])
			sent = True
	else:
		form = VideoShareForm()
	return render(request,
				  'videos/videos/share.html',
				  {'form': form,
				   'video': video,
				   'sent': sent})

@login_required
@require_POST
def video_like(request):
	video_id = request.POST.get('id')
	action = request.POST.get('action')
	try:
		video = VideoModel.objects.get(id=video_id)
		if action == 'like':
			video.users_like.add(request.user)
		else:
			video.users_like.remove(request.user)
		return JsonResponse({'status': 'ok'})
	except:
		pass
	return JsonResponse({'status': 'ok'})

videos/templates/videos/videos/create.html
{% extends "blog/base.html" %}
{% load bootstrap5 %}
{% block content %}
<title>Create Video</title>

<div class="container-fluid">
	{% if messages %}
		{% for message in messages %}
			<div class="alert alert-primary {{ message.tag }}"
				 rol="alert">
				 {{ message }}
			</div>
		{% endfor %}
	{% endif %}
	<div class="row">
		<div class="col-sm">
			<div class="g-0 border rounded 
			 			overflow-hidden flex-md-row
			 			mb-4 shadow-sm h-md-250 
			 			position-relative bg-dark text-white p-3">
            	<h1>Create Video</h1>
          	</div>
          	<div class="py-3">
				<div class="border p-4">
					<form action="."
			     		  method="post" 
			              enctype="multipart/form-data">
						{% bootstrap_form form %}
						{% csrf_token %}
						<button type="submit" class="btn btn-primary">
								Create Video
						</button>
					</form>
				</div>
			</div>
		</div>

		<div class="col-sm">
		</div>
	</div>
</div>
<br>
{% endblock %}

videos/templates/videos/videos/detail_videos.html
{% extends "blog/base.html" %}
{% load thumbnail %}
{% block content %}
{% load bootstrap5 %}

<title>Detail Video</title>

<div class="container">
	<div class="row">
			<video class="bg-dark" 
				   width="100px" 
				   height="400" 
				   controls="controls">
				<source src="{{ videos.upload.url }}" 
						type='video/mp4'>
				</source>
			</video>
		<div class="col-sm">
			<br>
			<div class="row">
				<div class="col-sm-6 col-4">
					<p class="fw-bold"
			   		   style="font-size: 20px">
						{{ videos.title }}
					</p>
				</div>
				<div class="col-sm-3 col-4">
					{% with total_likes=videos.users_like.count users_like=videos.users_like.all %}
						<a href="#"
					   	   data-id="{{ videos.id }}"
					       data-action="{% if request.user in users_like %}un
					   					{% endif %}like"
					   	   class="like btn btn-danger">
							{% if request.user not in  users_like %}
								Like
							{% else %}
								Unlike
							{% endif %}
						</a>
						<span class="count">
							<span class="total
										 btn
										 btn-success">
										{{ total_likes }}
							</span>
						</span>
					{% endwith %}
				</div>
				<div class="col-sm-3 col-4">
					<a href="{% url 'videos:video_share' videos.id %}">
						<button type="sumbit" 
								class="btn btn-outline-danger">
							<svg xmlns="http://www.w3.org/2000/svg"
							 	 width="16"
							 	 height="16"
							 	 fill="currentColor"
							 	 class="bi bi-share-fill"
							 	 viewBox="0 0 16 16">
  							<path d="M11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.499 2.499 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5z"/>
							</svg>
							<span class="px-2">
								Share
							</span>
						</button>
					</a>
				</div>
			</div>
			<div class="border"></div>
			<p class="fw-bold">
				{{ videos.author }}
			</p>
			<p>
				{{ videos.body }}
			</p>
			<div class="border"></div>
			<br>

			<form action="" method="post">
				{% bootstrap_form form %}
				{% csrf_token %}
				<button type="submit"
						class="btn btn-primary">
						Comment
				</button>
			</form>

			{% for comment in comments %}
				<div class="py-4">
					<span class="fw-bold" 
						  style="font-size: 13px">
							{{ comment.name }}
					</span>
					<span class="text-muted display-inline" 
						  style="font-size: 13px">
							{{ comment.created }}
					</span>
					<p class="pt-1">
						{{ comment.body }}
					</p>
				</div>
			{% endfor %}
			<br>
		</div>
		<div class="col-sm">
			{% for videos in similar_videos %}
			<a href="{{ videos.get_absolute_url }}">
				<div class="row py-2">
					<div class="col">
						{% thumbnail videos.poster "300x200" crop="100%" as im %}
							<img class="img-fluid"
					 			src="{{ im.url }}">
						{% endthumbnail %}
					</div>
					<div class="col">
						<h5 class="fw-bold">{{ videos.title }}</h5>
						<p class="text-muted">{{ videos.author }}</p>
						<p class="text-muted">{{ videos.created }}</p>
					</div>
				</div>
			</a>
			{% endfor %}
		</div>
	</div>
</div>

{% endblock %}


{% block domready %}
	$('a.like').click(function(e){
		e.preventDefault();
		$.post(
			'{% url "videos:like" %}',
			{id: $(this).data('id'),
			 action: $(this).data('action')
			},
			 function(data){
			 	if (data['status'] == 'ok'){
			 		var previous_action = $('a.like').data('action');

			 		$('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');

			 		$('a.like').text(previous_action == 'like' ? 'Unlike': 'Like');

			 		var previous_likes = parseInt($('span.count .total').text());
			 		$('span.count .total')
			 		.text(
			 			  previous_action == 'like' ? previous_likes + 1
			 			  : previous_likes - 1);


			 }
			}
		);	
	});
{% endblock %}

videos/templates/videos/videos/edit.html
{% extends "blog/base.html" %}
{% load bootstrap5 %}

{% block content %}
<title>Edit Video</title>

<div class="container-fluid">
	{% if messages %}
		{% for message in messages %}
			<div class="alert alert-primary {{ message.tag }}"
				 rol="alert">
				{{ message }}
			</div>
		{% endfor %}
	{% endif %}
	<div class="row">

		<div class="col-sm">
			<div class="g-0 border rounded 
						overflow-hidden flex-md-row mb-4 
						shadow-sm h-md-250 position-relative 
						bg-dark text-white p-3">
            <h1>Edit Video</h1>
            </div>
            <div class="py-3">
            	<div class="border p-4">
					<form action="." 
			      		  method="post"
			              enctype="multipart/form-data">
			      		{% bootstrap_form form %}
			      		{% csrf_token %}
			      		<button type="submit"
			      		  		class="btn btn-primary">
			      	  	  		Save
			      		</button>
		    		</form>
		    	</div>
		    </div>
		</div>
		<div class="col-sm">
		</div>
	</div>
</div>
<br>
{% endblock %}

videos/templates/videos/videos/list_ajax.html
{% load thumbnail %}

<title>List Videos</title>

<div class="container-fluid">
  <div class="row 
  			  row-cols-2
              row-cols-sm-2 
              row-cols-md-4 g-1">
    {% for video in videos %}
      <div class="col">
        <a href="{{ video.get_absolute_url }}">
          {% thumbnail video.poster "300x200" crop="100%" as im %}
            
            <image class="img-fluid" 
                   src="{{ im.url }}"></image>
          {% endthumbnail %}
        </a>
        <div class="card-body">
          <div class="text-left">
       		<span class="fw-bold">
       			{{ video.title }}
       		</span>
       		<div class="text-muted"
       		 	  style="font-size: 12px">
       		 	  <span class="fw-bold"
       		 	  	    style="font-size: 14px">
       		 	  	    {{ video.author }} |
       		 	  </span>
       		 	  {{ video.created }}
       		 </div>
          </div> 
        </div>
      </div>
    {% endfor %}
  </div>
</div>

videos/templates/videos/videos/list_videos.html
{% extends "blog/base.html" %}
{% load thumbnail %}

{% block content %}
<div id="videos-list">
    {% include "videos/videos/list_ajax.html" %}
</div>
{% endblock content %}

{% block domready %}
  var page = 1;
  var empty_page = false;
  var block_request = false;

  $(window).scroll(function () {
    var margin = $(document).height()
                 - $(window).height()
                 - 200;
    if  ($(window).scrollTop() > margin
         && empty_page == false
         && block_request == false) {

         block_request = true;
         page += 1;

         $.get('?page=' + page, function (data) {
            if (data == '') {
                empty_page = true;
            } else {
                block_request = false;
                $('#videos-list').append(data);
            }
        });
      }
    });
{% endblock %}


videos/templates/videos/videos/my_videos.html
{% extends "blog/base.html" %}
{% load thumbnail %}

{% block content %}
    <div id="my-videos">
        <div class="container-fluid">
            <div class="g-0 border rounded 
                 overflow-hidden flex-md-row mb-4 
                 shadow-sm h-md-250 position-relative 
                 bg-dark text-white p-3 text-center">
                 <h1>My video</h1>
            </div>
        </div>
        {% include "videos/videos/my_videos_ajax.html" %}
    </div>
{% endblock  %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;

    $(window).scroll(function () {
        var margin = $(document).height()
                     - $(window).height()
                     - 200;
        if ($(window).scrollTop() > margin
            && empty_page == false
            && block_request == false) {

            block_request = true;
            page += 1;

            $.get('?page=' + page, function (data) {
                if (data == '') {
                    empty_page = true;
                } else {
                    block_request = false;
                    $('#my-videos').append(data);
                }
            });
        }
    });

{% endblock %}

videos/templates/videos/videos/my_videos_ajax.html
{% load thumbnail %}

<title>My videos</title>

<div class="container-fluid">
  <div class="row 
              row-cols-2
              row-cols-sm-2 
              row-cols-md-4 g-3">
    {% for video in my_videos %}
      <div class="col">
        <a href="{{ video.get_absolute_url }}">
          {% thumbnail video.poster "300x200" crop="100%" as im %}
            
            <image class="img-fluid rounded 
                          mx-auto d-block" 
                   src="{{ im.url }}"></image>
          {% endthumbnail %}
        </a>
        <div class="card-body">
          <div class="text-center">
       		<span class="fw-bold">
       			{{ video.title }} | <a href="{% url 'videos:edit' video.id %}">edit</a>
       		</span>
       		<div class="text-muted"
       		 	  style="font-size: 12px">
       		 	  <span class="fw-bold"
       		 	  	style="font-size: 14px">
       		 	  	{{ video.author }} |
       		 	  </span>
       		 	  {{ video.created }}
       		 </div>
          </div> 
        </div>
      </div>
    {% endfor %}
  </div>
</div>

videos/templates/videos/videos/share.html
{% extends "blog/base.html" %}
{% load bootstrap5 %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm col-12">
			<div class="border p-4">
				{% if sent %}
					<h1>Email successfully sent</h1>
					<p>"{{ video.title }}" 
						was succesfully sent to 
						{{ form.cleaned_date.to }}.
					</p>
				{% else %}
					<h2>Share "{{ video.title }}" email</h2>
					<form action="" method="post">
						{% bootstrap_form form %}
						{% csrf_token %}
						<button type="submit"
								class="btn btn-primary">
								Video Share
						</button>
					</form>
				{% endif %}
			</div>
		</div>
		<div class="col-sm col">
		</div>
	</div>
</div>
<br>
{% endblock content %}