blog/urls.py
from django.urls import path
from .import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
	# Обработчики приложения блога.
	path('', views.post_list, name='post_list'),
	# path('', views.PostListView.as_view(), name='post_list'),
	path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),

	path('<int:year>/<int:month>/<int:day>/<slug:post>/',
		views.post_detail, name='post_detail'),
	path('<int:post_id>/share/', views.post_share, name='post_share'),
	path('feed/', LatestPostsFeed(), name='post_feed'),

	path('create/', views.create_post, name='create_post'),
	path('my_posts', views.my_posts, name='my_posts'),
	path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),

	path('journal/', views.journal, name='journal'),
	path('like/', views.post_like, name='like')


	
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {'posts': PostSitemap, }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
    	name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('videos/', include('videos.urls', namespace='videos')),
    path('search/', include('search.urls', namespace='search'))
   

   
   
   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.conf import settings 

# Create your models here.

# Менеджер моделя POST
class PublishedManager(models.Manager):
	def get_queryset(self):
		return super().get_queryset().filter(status='published')

# Модель для Постов
class Post(models.Model):
	objects = models.Manager()
	published = PublishedManager()
	tags = TaggableManager()
	

	STATUS_CHOICES = (
		('draft', 'Draft'),
		('published', 'Published'),

		)
	


	title = models.CharField(max_length=40)
	slug = models.SlugField(max_length=250, unique_for_date='publish')
	author = models.ForeignKey(User, on_delete=models.CASCADE,
								related_name='blog_posts')
	body = models.TextField()
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	image = models.ImageField(upload_to="images/%Y/%m/%d", blank=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10,
							  choices=STATUS_CHOICES,
							  default='draft')

	users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
										related_name='blog_like',
										blank=True)
	total_likes = models.PositiveIntegerField(db_index=True,
											  default=0)
	
	class Meta:
		ordering = ('-publish' ,)
	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post_detail', args=[self.publish.year,
						self.publish.month, self.publish.day, self.slug])

# Модель для комментариев
class Comment(models.Model):
	post = models.ForeignKey(Post, 
							 on_delete=models.CASCADE,
							 related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now_add=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('created' ,)
	def __str__(self):
		return 'Comment by {} on {}'.format(self.name, self.post)


blog/forms.py
from django import forms
from .models import Comment, Post

# Форма отправки письмо по email
class EmailPostForm(forms.Form):
	name = forms.CharField(max_length=25)
	#email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False, widget=forms.Textarea)

# Форма комментирование
class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('email', 'body')



# Форма Создание Поста
class CreatePostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('tags', 'title', 'slug',
				  'body', 'publish', 'image',
				  'status')


blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage,\
								  PageNotAnInteger
from .models import Post, Comment
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, \
								  CreatePostForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .tasks import comment_add
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from videos.models import VideoModel



# Обработчик для отправки письмо по Email
def post_share(request, post_id):
	# Получение статьи по идентификатуру.
	post = get_object_or_404(Post, id=post_id, status='published')
	sent = False
	if request.method == 'POST':
		# Форма была отправлена на сохранение.
		form = EmailPostForm(request.POST)
		if form.is_valid():
			# Все поля формы прошли валидацию
			cd = form.cleaned_data
			# Отправка электронной почты.
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], 
														    'kajnazarov06@mail.ru', 
				                            			    post.title)
			message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, 
															 post_url, 
				               								 cd['name'], 
															 cd['comments'])
			send_mail(subject, message, 
				      'kajnazarov06@mail.ru', [cd['to']])
			sent = True
	else:
		form = EmailPostForm()
	return render(request, 'blog/post/share.html',
				{'post': post, 
				 'form': form, 
				 'sent': sent})

# обработчик для главной страницы
class PostListView(ListView):
	queryset = Post.published.all()
	context_object_name = 'posts'
	paginate_by = 3
	template_name = 'blog/post/list.html'

# обработчик для главной страницы
def post_list(request, tag_slug = None):
	object_list = Post.published.all()
	tag = None

	if tag_slug:
		tag = get_object_or_404(Tag, slug = tag_slug)
		object_list = object_list.filter(tags__in = [tag])		

	paginator = Paginator(object_list, 3) # По 4 статьи на каждой странице.
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		# Если страница не является целым числом, возвращаем первую страницу.
		posts = paginator.page(1)
	except EmptyPage:
		# Если намер страницы больше, чем общее количество страниц, возвращаем последнюю.
		posts = paginator.page(paginator.num_pages)
	return render(request, 
				  'blog/post/list.html', 
				  {'page': page, 
				   'posts': posts,
				   'tag': tag})

# обрабочик для детального преставление 
def post_detail(request, year, month, day, post, tag_slug = None):
	object_list = Post.published.all()
	tag = None

	if tag_slug:
		tag = get_object_or_404(Tag, slug = tag_slug)
		object_list = object_list.filter(tags__in = [tag])
	


	post = get_object_or_404(Post, slug=post, 
								   status='published', 
							       publish__year=year,
							       publish__month=month,
							       publish__day=day)
	# Список активных комментариев для этой статьи.
	comments = post.comments.filter(active=True)
	new_comment = None
	if request.method == 'POST':
		# Пользователь отправил комментарий.
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			# Создаем комментарий, но покане сохраняем в базе данных.
			new_comment = comment_form.save(commit=False)
			new_comment.name = request.user.username
			# Привязываем комментарий к текущей статье.
			new_comment.post = post
			# Сохраняем комментарий в базе данных.
			new_comment.save()
			comment_add(new_comment.id)
	else:
		comment_form = CommentForm()

	# Формирование списка похожих статей.
	post_tags_ids = post.tags.values_list('id', flat=True)
	similar_posts = Post.published.filter(tags__in = post_tags_ids)\
								  .exclude(id = post.id)
	similar_posts = similar_posts.annotate(same_tags = Count('tags'))\
								  .order_by('-same_tags', '-publish')[:4]

	return render(request, 
		          'blog/post/detail.html', 
		          {'post': post,
				   'comments': comments,
				   'new_comment': new_comment,
				   'comment_form': comment_form,
				   'similar_posts': similar_posts,
				   'tag': tag,})

# обрабочик создание постов
@login_required
def create_post(request):
	if request.method == 'POST':
		create_form = CreatePostForm(data=request.POST,
									 files=request.FILES)
		if create_form.is_valid():
			new_post = create_form.save(commit=False)
			new_post.author = request.user
			new_post.save()
			messages.success(request, 'Post created successfully')
		else:
			messages.error(request, 'Error when creating a post')
	else:
		create_form = CreatePostForm()

	context = {'create_form': create_form}
	return render(request, 
		          'blog/post/create_post.html', 
		         context)

# обрабочик для сортирования личных постов
@login_required
def my_posts(request):
	posts = Post.objects.filter(author=request.user.id)
	paginator = Paginator(posts, 3)
	page = request.GET.get('page')

	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		if request.is_ajax():
			return HttpResponse('')
			posts = paginator.page(paginator.num_pages)

	if request.is_ajax():
		return render(request,
					  'blog/post/my_posts_ajax.html',
					  {'posts': posts})
		
	return render(request, 
		          'blog/post/my_posts.html', 
		          {'posts': posts})

# обрабочик для редактирования постов
@login_required
def edit_post(request, post_id):
	post = Post.objects.get(id=post_id)
	
	if request.method == 'POST':
		post_form = CreatePostForm(instance=post,
								   data=request.POST,
								   files=request.FILES)
		
		if post_form.is_valid():
			post_form.save()
			messages.success(request, 'Post saved successfully')
		else:
			messages.error(request, 'Error while saving post')
	else:
		post_form = CreatePostForm(instance=post)

	return render(request, 
		          'blog/post/edit_post.html', 
		          {'post_form': post_form,
				   'post': post,})

# Обрабочик описание журнала
def journal(request):
	return render(request, 
		          'blog/journal/about_journal.html')

@login_required
@require_POST
def post_like(request):
	post_id = request.POST.get('id')
	action = request.POST.get('action')
	try:
		post = Post.objects.get(id=post_id)
		if action == "like":
			post.users_like.add(request.user)
		else:
			post.users_like.remove(request.user)
		return JsonResponse({'status': 'ok'})
	except:
		pass
	return JsonResponse({'status': 'ok'})



blog/templates/blog/post/create_post.html
{% extends "blog/base.html" %}
{% load bootstrap5 %}

{% block content %}
<title>Create Post</title>
<div class="container-fluid">
	{% if messages %}
		{% for message in messages %}
			<div class="alert alert-primary {{ message.tags }}"
				role="alert">{{ message|safe }}
			</div>
		{% endfor %}
	{% endif %}
	
	<div class="row">
		<div  class="col-md-8 col-xs-12">
			<div class="g-0 border rounded 
						overflow-hidden flex-md-row mb-4 
						shadow-sm h-md-250 position-relative 
						bg-dark text-white p-3">
  				<h1>Create Post</h1>
			</div>
			<div class="py-3">
				<div class="border p-4">
					<form action="." 
				          method="post" 
				          enctype="multipart/form-data">
						{% bootstrap_form create_form %}
						{% csrf_token %}
						<button type="submit" 
								class="btn btn-primary">
								Create Post
						</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<br>
{% endblock %}

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% load bootstrap5 %}
{% load thumbnail %}



{% block content %}
<title>Post detail</title>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-xs-12 p-4 
					col-sm-12 d-flex flex-column 
					position-static">
			<div class="fw-bold">NEWS</div> 
			<div class="text-muted">
				| {{ post.publish }}
			</div>
			<h1 class="py-2 fw-bold">
				{{ post.title }}
			</h1>
			<p>{{ post.body }}</p>
			<div class="border-top py-2"></div>
			<div class="row">
    			<div class="col-sm-7 col-4">
					{% with comments.count as comments_total %}
						<p class="fw-bolder" 
							style="font-size: 17px">
							{{ comments_total }} 
								comment 
							{{ comments_total|pluralize }}
						<p>
					{% endwith %}
				</div>
				<div class="col-sm-2 col-4">
					{% with total_likes=post.users_like.count users_like=post.users_like.all %}
						<a href="#"
					   	   data-id="{{ post.id }}"
					       data-action="{% if request.user in users_like %}un
					   					{% endif %}like"
					   	   class="like btn btn-danger">
							{% if request.user not in  users_like %}
								Like
							{% else %}
								Unlike
							{% endif %}
						</a>
						<span class="count">
							<span class="total
										 btn
										 btn-success">
										{{ total_likes }}
							</span>
						</span>
					{% endwith %}
				</div>
				<div class="col-sm-3 col-4">
					<a href="{% url 'blog:post_share' post.id %}">
						<button type="sumbit" 
								class="btn btn-outline-danger">
							<svg xmlns="http://www.w3.org/2000/svg"
								 width="16"
								 height="16"
								 fill="currentColor"
								 class="bi bi-share-fill"
								 viewBox="0 0 16 16">
  							<path d="M11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.499 2.499 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5z"/>
							</svg>
							<span class="px-2">
								Share
							</span>
						</button>
					</a>
				</div>
			</div>
			<h2 class="py-3">
				Leave a comment
			</h2>
			<form class="py-4" acton="" method="post">
				{% bootstrap_form comment_form %}
				{% csrf_token %}
				<button type="sumbit" 
						class="btn btn-primary">
						Comment
				</button>
			</form>
			{% for comment in comments %}
				<div class="py-4">
					<span class="fw-bold" 
						  style="font-size: 13px">
							{{ comment.name }}
					</span>
					<span class="text-muted display-inline" 
						  style="font-size: 13px">
							{{ comment.created }}
					</span>
					<p class="pt-1">
						{{ comment.body }}
					</p>
				</div>
			{% endfor %}
		</div>
		<div class="col-md-4 col-xs-12  
					col-sm-12 p-4 d-flex 
					flex-column position-static">
			<span class="g-0 border rounded 
						overflow-hidden 
						flex-md-row mb-4 shadow-sm 
						h-md-250 position-relative"><br>
			</span>
			<h1 class="fw-bold" 
				style="font-size: 20px">
				Related Articles</h1>
			{% for post in similar_posts %}
			<a href="{{ post.get_absolute_url }}" 
				style="color: #000000; 
					   text-decoration:none">
			<div class="row border-bottom py-2">
				<div class="col-md-9 
							col-xs-8
							col-sm-8">
					<span class="fw-bold py-1">
						{{ post.title }}
					</span>
				</div>
				<div class="col-md-3 
							col-xs-4  
							col-sm-4">
				<img class="py-1" 
					 style="width: 110px; 
					 		height: 100px" 
					 src="{{ post.image.url }}">
				</div>
			</div>
			</a>		
			{% endfor %}
			<h1 class="pt-4 fw-bold" 
				style="font-size: 20px">
				Subjects
			</h1>
			{% for tag in post.tags.all %}
 				<a class="badge bg-info text-white" 
 				   style="width: 80px" 
 				   href="{% url 'blog:post_list_by_tag' tag.slug %}">
 				   {{ tag.name }}
 				</a>
 			{% endfor %}
 			<div class="row border-bottom py-2">
 			</div>			
		</div>
	</div>
</div>
{% endblock %}

{% block domready %}
	$('a.like').click(function(e){
		e.preventDefault();
		$.post(
			'{% url "blog:like" %}',
			{id: $(this).data('id'),
			 action: $(this).data('action')
			},
			 function(data){
			 	if (data['status'] == 'ok'){
			 		var previous_action = $('a.like').data('action');

			 		$('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');

			 		$('a.like').text(previous_action == 'like' ? 'Unlike': 'Like');

			 		var previous_likes = parseInt($('span.count .total').text());
			 		$('span.count .total')
			 		.text(
			 			  previous_action == 'like' ? previous_likes + 1
			 			  : previous_likes - 1);


			 }
			}
		);	
	});
{% endblock %}

blog/templates/blog/post/edit_post.html
{% extends "blog/base.html" %}
{% load bootstrap5 %}

{% block content %}
<title>Edit Post</title>
<div class="container-fluid">
	{% if messages %}
		{% for message in messages %}
			<div class="alert alert-primary {{ message.tags }}"
				 rol="alert">
				 {{ message }}
			</div>
		{% endfor %}
	{% endif %}
	<div class="row">
		<div  class="col-md-8 col-xs-12">
			<div class="g-0 border rounded overflow-hidden
					   flex-md-row mb-4 shadow-sm h-md-250
					   position-relative bg-dark text-white p-3">
  				<h1>Edit Post</h1>
			</div>
			<div class="py-3">
				<div class="border p-4">
					<form action="{% url 'blog:edit_post' post.id %}"
				  		  method="post" 
				          enctype="multipart/form-data">
						{% bootstrap_form post_form %}
						{% csrf_token %}
						<button type="submit" 
								class="btn btn-primary">
								Change
						</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<br>

{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
	{% for post in latest_posts %}
		<li class="pb-2"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
	{% endfor %}
</ul>


blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load thumbnail %}


{% block content %}
<title>List Post</title>

<div class="album py-5 bg-light">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-md-6">
        <div class="row g-0 border 
                    rounded overflow-hidden
                    flex-md-row mb-4 shadow-sm
                    h-md-250 position-relative">
          <div class="col p-4 d-flex
                      flex-column 
                      position-static">
            <h3 class="p-3 mb-2 bg-info text-white shadow-lg">
              Latest Post
            </h3>
            {% show_latest_posts 3 %}
          </div>
          <div class="col-auto d-none d-lg-block">
            <svg class="bd-placeholder-img" 
                 width="200"
                 height="250" 
                 xmlns="http://www.w3.org/2000/svg" 
                 role="img"
                 aria-label="Placeholder: Thumbnail" 
                 preserveAspectRatio="xMidYMid slice" 
                 focusable="false">
                  <title>
                    Placeholder
                  </title>
                 <rect width="100%" 
                       height="100%"
                       fill="#55595c"/>
                 <text x="50%"
                       y="50%"
                       fill="#eceeef"
                       dy=".3em">
                </text>
            </svg>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="row g-0 border 
                    rounded overflow-hidden
                    flex-md-row mb-4 shadow-sm
                    h-md-250 position-relative">
          <div class="col p-4 d-flex 
                      flex-column position-static">
            <h3 class="p-3 mb-2 bg-danger shadow-lg text-white">
              Popular
            </h3>
            {% get_most_commented_posts as get %}
            {% for post in get %}
              <li><a href="{{ post.get_absolute_url }}">
                    {{ post.title|truncatewords:2 }}
                  </a>
              </li>
            {% endfor %} 
          </div>
          <div class="col-auto 
                      d-none d-lg-block">
            <svg class="bd-placeholder-img" 
            width="200" height="250" xmlns="http://www.w3.org/2000/svg" 
            role="img" aria-label="Placeholder: Thumbnail" 
            preserveAspectRatio="xMidYMid slice" 
            focusable="false"><title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"/>
            <text x="50%" y="50%" fill="#eceeef" dy=".3em"></text></svg>
          </div>
        </div>
      </div>
    </div>
    <div class="row row-cols-1 
                row-cols-sm-2 
                row-cols-md-3 g-3">
      {% for post in posts %}
        <div class="col-12">
          <div class="card shadow-sm">
            {% thumbnail post.image "200x200" crop="100%" as im %} 
              <image src="{{ im.url }}" 
                     class="img-fluid">
                     <title>
                        Placeholder
                      </title>
              </image>
            {% endthumbnail %}
            <a href="{{ post.get_absolute_url }}" 
               style="text-decoration: none; color: #000000;">
              <div class="card-body">
                <h1 class="fw-bold">
                  {{ post.title|truncatewords:2 }}
                </h1>
                <p class="" style="font-size: 15px">
                  {{ post.title|truncatewords:3 }}
                </p>
                <p class="text-muted pt-4">
                  {{ post.author }}
                </p>
                <span class="fw-bold" 
                      style="font-size: 13px">
                      News | 
                </span> 
                <span class="text-muted" 
                      style="font-size: 13px">
                      {{ post.publish }}
                </span>
            </a>
          </div>
        </div>
    </div>
      {% endfor %}
    </div>
  </div>
</div>

{% if page.has_previos %}
  <a href="?page={{ page.previous_page_number }}">Previous</a>
{% endif %}
{% include "pagination.html" with page=posts %}
<br>
{% endblock %}


blog/templates/blog/post/my_posts.html
{% extends "blog/base.html" %}
{% load thumbnail %}

{% block content %}
<div id="my-posts">
    <div class="container-fluid">
        <div class="g-0 border rounded 
                    overflow-hidden 
                    flex-md-row mb-4 shadow-sm
                    h-md-250 position-relative 
                    bg-dark text-white p-3 text-center">
                    <h1>My Post</h1>
        </div>
    </div>
    {% include "blog/post/my_posts_ajax.html" %}
</div>
{% endblock %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;

    $(window).scroll(function () {
        var margin = $(document).height()
                     - $(window).height()
                     - 200;
        if ($(window).scrollTop() > margin
            && empty_page == false
            && block_request == false) {

            block_request = true;
            page += 1;

            $.get('?page=' + page, function (data) {
                if (data == '') {
                    empty_page = true;
                } else {
                    block_request = false;
                    $('#my-posts').append(data);
                }
            });
        }
    });
{% endblock %}

blog/templates/blog/post/my_posts_ajax.html
{% load thumbnail %}

<title>My post</title>

<div class="album py-2 bg-light">
  <div class="container-fluid">
    <div class="row row-cols-1
                row-cols-sm-2
                row-cols-md-3 g-3">
      {% for post in posts %}
        <div class="col-12">
          <div class="card shadow-sm">
            {% thumbnail post.image "200x200" crop="100%" as im %}
              <image src="{{ im.url }}" 
                     class="image-fluid">
                <title>Placeholder</title>
              </image>
            {% endthumbnail %}
            <a href="{{ post.get_absolute_url }}" 
               style="text-decoration: none; color: #000000;">
              <div class="card-body">  
                <h1 class="fw-bold">
                  {{ post.title|truncatewords:2 }}
                </h1>
                <p class="" 
                   style="font-size: 15px">
                   {{ post.title|truncatewords:3 }}
                </p>
                <p class="text-muted pt-4">
                  {{ post.author }}
                </p>
                <a href="{% url 'blog:edit_post' post.id %}">
                  <button class="btn btn-primary">
                    Edit a post
                  </button>
                </a>
             </a>
            </div>
          </div>
        </div>
  {% endfor %}
      </div>
  </div>
</div>

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% load bootstrap5 %}

{% block title %}Share a post{% endblock %}

{% block content %}
<title>Share</title>
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-6">
			<div class="border p-3">
				{% if sent %}
					<h1>Email successfully sent</h1>
					<p>"{{ post.title }}" 
						was succesfully sent to 
						{{ form.cleaned_date.to }}.
					</p>
				{% else %}
					<h1>Share "{{ post.title }}"
					 	by e-mail
					</h1>
					<form action="." method="post">
						{% bootstrap_form form %}
						{% csrf_token %}
						<button type="btn" 
								class="btn btn-primary">
								Send e-mail
						</button>
					</form>
				{% endif %}
			</div>
		</div>
		<div class="col-sm-6">
		</div>
	</div>
</div>

<br>
{% endblock %}
